twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        SITE_NAME: Pierre Pineau
        CONTACT_EMAIL: contact@pierrepineau.fr
        CLIENT_FAVICON_COLOR: "#419FCC"
        CLIENT_FAVICON_BG: "#1f272f"
        socials: [
            {
                'icon': "fa-brands fa-linkedin-in",
                'name': "Me contacter sur linkedin",
                'url': "https://www.linkedin.com/in/pierre-pineau-pro/",
            },
        ]
        menu: [
            {
                'name': "À propos de moi",
                'url': "#a-propos",
            },
            {
                'name': "Expériences",
                'url': "#experiences",
            },
            {
                'name': "Réalisations",
                'url': "#realisations",
            },
            {
                'name': "Compétences",
                'url': "#competences",
            },
            {
                'name': "Contact",
                'url': "#contact",
            }
        ]
        statistics: [
            {
                'name': "Expériences professionnelles",
                'value': "2 ans",
            },
            {
                'name': "Passé en entreprise",
                'value': "+800 h",
            },
            {
                'name': "de nuit blanche passé sur des projets",
                'value': "+20h",
            },
            
        ]

        specialties: [
            {
                'icon': "fa-solid fa-cube",
                'name': "Web Design",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-microchip",
                'name': "Web developpement",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-gears",
                'name': "Référencement",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-film",
                'name': "Motion design",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            }
        ]
        skills: [
            {
                'icon': "fa-brands fa-symfony",
                'name': "Symfony",
                'value': 80,
            },
            {
                'icon': "fa-brands fa-laravel",
                'name': "Laravel",
                'value': 55,
            },
            {
                'icon': "fa-brands fa-vuejs",
                'name': "VueJS",
                'value': 50,
            },
            {
                'icon': "fa-solid fa-file-code",
                'name': "Tailwind",
                'value': 90,
            },
            {
                'icon': "fa-brands fa-square-js",
                'name': "Javascript",
                'value': 90,
            },
            {
                'icon': "fa-solid fa-code",
                'name': "TWIG",
                'value': 80,
            },
        ]

        works: [
            {
                'name': work.innovdata.name,
                'job': work.job.dev,
                'type': work.type.alternance,
                'startAt': "2021-08-25 00:00:00",
                'endAt': null,
                'site': 'https://innov-data.com/',
                'content': work.innovdata.content
                # 'duration': "Alternance"
            },
            {
                'name': work.expertviseo.name,
                'job': work.job.dev,
                'type': work.type.stage,
                'startAt': "2020-04-29 00:00:00",
                'endAt': "2020-06-29 00:00:00",
                'site': 'https://www.expert-viseo.fr/',
                'content': work.expertviseo.content
                # 'duration': "Alternance"
            },
        ]

        projects: [
            {
                'name': "Find Your Horse",
                'thumbnail': find-your-horse/find-your-horse,
                'categorie': "Innov'data",
                'url': "https://www.find-your-horse.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Template Lucie - Centre équestre d'Idoine",
                'thumbnail': template-lucie/template-lucie,
                'categorie': "Innov'data",
                'url': "https://centre-equestre-ecurie-didoine.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Template Léo - Ecurie d'Estang",
                'thumbnail': template-leo/template-leo,
                'categorie': "Innov'data",
                'url': "https://ecuriesestang.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Template Arthur - Ecurie d'Estang",
                'thumbnail': template-arthur/template-arthur,
                'categorie': "Innov'data",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "French DTF",
                'thumbnail': french-dtf/french-dtf,
                'categorie': "Innov'data",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Maquette pays Basque",
                'thumbnail': maquettes-ui-pays-basque/maquettes-ui-pays-basque,
                'categorie': "Projet d'école",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Maquette Produit Tech",
                'thumbnail': maquettes-ui-produit-tech/maquettes-ui-produit-tech,
                'categorie': "Projet d'école",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Motion design - Logo",
                'thumbnail': find-your-horse/find-your-horse,
                'categorie': "Projet d'école",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Motion design - Rest'au Frigo",
                'thumbnail': find-your-horse/find-your-horse,
                'categorie': "Projet d'école",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Motion design - Kaze",
                'thumbnail': find-your-horse/find-your-horse,
                'categorie': "Projet d'école",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Kaze",
                'thumbnail': kaze/kaze,
                'categorie': "Projet d'école",
                'url': "https://www.find-your-horse.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Rest'au Frigo",
                'thumbnail': rest-au-frigo/rest-au-frigo,
                'categorie': "Projet d'école",
                'url': "https://rest-au-frigo.netlify.app/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },                  
        ]
        

when@test:
    twig:
        strict_variables: true
