twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        SITE_NAME: Pierre Pineau
        CONTACT_EMAIL: contact@pierrepineau.fr
        CLIENT_FAVICON_COLOR: "#419FCC"
        CLIENT_FAVICON_BG: "#1f272f"
        socials: [
            {
                'icon': "fa-brands fa-linkedin-in",
                'name': "Me contacter sur linkedin",
                'url': "https://www.linkedin.com/in/pierre-pineau-pro/",
            },
        ]
        menu: [
            {
                'name': "À propos de moi",
                'url': "#a-propos",
            },
            {
                'name': "Expériences",
                'url': "#experiences",
            },
            {
                'name': "Réalisations",
                'url': "#realisations",
            },
            {
                'name': "Compétences",
                'url': "#competences",
            },
            {
                'name': "Contact",
                'url': "#contact",
            }
        ]
        statistics: [
            {
                'name': "Expériences professionnelles",
                'value': "2 ans",
            },
            {
                'name': "Passées en entreprise",
                'value': "+800 h",
            },
            {
                'name': "Nuit blanche passée sur des projets",
                'value': "+20 h",
            }, 
        ]

        specialties: [
            {
                'icon': "fa-solid fa-pen-to-square",
                'animation': "web-design",
                'name': "Web Design",
                'content': "Conception d'interfaces attrayantes, intuitives et responsives en utilisant les principes du design graphique et de l'ergonomie pour créer des expériences visuelles captivantes et mémorables",
            },
            {
                'icon': "fa-solid fa-microchip",
                'animation': "dev",
                'name': "Web developpement",
                'content': "Création de sites dynamiques et interactifs en utilisant les dernières technologies front-end et back-end pour offrir des expériences utilisateur exceptionnelles et des fonctionnalités avancées",
            },
            {
                'icon': "fa-solid fa-gears",
                'animation': "seo",
                'name': "Référencement",
                'content': "Amélioration de la visibilité en ligne grâce à des stratégies SEO efficaces et à l'optimisation du site web, incluant la vitesse de chargement, le contenu et les performances globales",
            },
            {
                'icon': "fa-solid fa-film",
                'animation': "motion-design",
                'name': "Motion design",
                'content': "Création d'animations visuelles percutantes et engageantes pour dynamiser les contenus et communiquer efficacement les messages clés, apportant ainsi une dimension visuelle et immersive aux projets web.",
            }
        ]
        skills: [
            {
                'icon': "fa-brands fa-symfony",
                'name': "Symfony",
                'value': 80,
            },
            {
                'icon': "fa-brands fa-laravel",
                'name': "Laravel",
                'value': 55,
            },
            {
                'icon': "fa-brands fa-vuejs",
                'name': "VueJS",
                'value': 50,
            },
            {
                'icon': "fa-solid fa-file-code",
                'name': "Tailwind",
                'value': 90,
            },
            {
                'icon': "fa-brands fa-square-js",
                'name': "Javascript",
                'value': 90,
            },
            {
                'icon': "fa-solid fa-code",
                'name': "TWIG",
                'value': 80,
            },
        ]

        works: [
            {
                'name': work.innovdata.name,
                'job': work.job.dev,
                'type': work.type.alternance,
                'startAt': "2021-08-25 00:00:00",
                'endAt': null,
                'site': 'https://innov-data.com/',
                'content': work.innovdata.content
                # 'duration': "Alternance"
            },
            {
                'name': work.expertviseo.name,
                'job': work.job.dev,
                'type': work.type.stage,
                'startAt': "2020-04-29 00:00:00",
                'endAt': "2020-06-29 00:00:00",
                'site': 'https://www.expert-viseo.fr/',
                'content': work.expertviseo.content
                # 'duration': "Alternance"
            },
        ]

        projects: [
            {
                'name': "Template Lucie - Centre équestre d'Idoine",
                'thumbnail': template-lucie/template-lucie,
                'categorie': "Innov'data",
                'url': "https://centre-equestre-ecurie-didoine.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Template Léo - Ecurie d'Estang",
                'thumbnail': template-leo/template-leo,
                'categorie': "Innov'data",
                'url': "https://ecuriesestang.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Template Arthur - Ecurie d'Estang",
                'thumbnail': template-arthur/template-arthur,
                'categorie': "Innov'data",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "French DTF",
                'thumbnail': french-dtf/french-dtf,
                'categorie': "Innov'data",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Maquette Produit Tech",
                'thumbnail': maquettes-ui-produit-tech/maquettes-ui-produit-tech,
                'categorie': "Projet d'école",
                'url': "",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Motion design - Logo",
                'thumbnail': find-your-horse/find-your-horse,
                'categorie': "Projet d'école",
                'url': "https://www.lesecuriesdelacanterie.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },                 
        ]
        

when@test:
    twig:
        strict_variables: true
