twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        SITE_NAME: Pierre Pineau
        CONTACT_EMAIL: contact@pierrepineau.fr
        
        socials: [
            {
                'icon': "fa-brands fa-linkedin-in",
                'name': "Me contacter sur linkedin",
                'url': "",
            },
        ]
        menu: [
            {
                'name': "À propos de moi",
                'url': "#a-propos",
            },
            {
                'name': "Expériences",
                'url': "#experiences",
            },
            {
                'name': "Réalisations",
                'url': "#realisations",
            },
            {
                'name': "Compétences",
                'url': "#competences",
            },
            {
                'name': "Contact",
                'url': "#contact",
            }
        ]
        statistics: [
            {
                'name': "d'expérience professionnelle",
                'value': "2 ans",
            },
            {
                'name': "lorem ipusm dolor sit",
                'value': "15",
            },
            {
                'name': "lorem ipusm dolor sit",
                'value': "+200 h",
            },
        ]

        specialties: [
            {
                'icon': "fa-solid fa-layer-group",
                'name': "Lorem ipusm dolor sit",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-layer-group",
                'name': "Lorem ipusm dolor sit",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-layer-group",
                'name': "Lorem ipusm dolor sit",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-layer-group",
                'name': "Lorem ipusm dolor sit",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            }
        ]
        skills: [
            {
                'icon': "fa-brands fa-symfony",
                'name': "Symfony",
                'value': 70,
            },
            {
                'icon': "fa-brands fa-symfony",
                'name': "Laravel",
                'value': 70,
            },
            {
                'icon': "fa-brands fa-symfony",
                'name': "VueJS",
                'value': 70,
            },
            {
                'icon': "fa-brands fa-symfony",
                'name': "Tailwind",
                'value': 70,
            },
            {
                'icon': "fa-brands fa-symfony",
                'name': "PHP",
                'value': 70,
            },
            {
                'icon': "fa-brands fa-symfony",
                'name': "CSS/SCSS",
                'value': 70,
            },
            {
                'icon': "fa-brands fa-symfony",
                'name': "Javascript",
                'value': 70,
            },
            {
                'icon': "fa-brands fa-symfony",
                'name': "TWIG",
                'value': 70,
            },
        ]

        works: [
            {
                'name': "Innov'data",
                'job': "Développeur web",
                'type': "Alternance",
                'startAt': "2020-05-25 00:00:00",
                'endAt': null,
                'site': 'https://innov-data.com/',
                'content': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt.'
                # 'duration': "Alternance"
            },
            {
                'name': "Expert Viséo",
                'job': "Développeur web",
                'type': "Stage",
                'startAt': "2020-05-25 00:00:00",
                'endAt': "2020-05-25 00:00:00",
                'site': 'https://www.expert-viseo.fr/',
                'content': 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt.'
                # 'duration': "Alternance"
            },
        ]

        achievements: [
            {
                'name': "Innov'data",
                'job': "Développeur web",
                'type': "Alternance",
                'startAt': "2020-05-25 00:00:00",
                'endAt': null,
                'site': 'url',
                'content': ''
                # 'duration': "Alternance"
            },
            {
                'name': "Expert Viséo",
                'job': "Développeur web",
                'type': "Stage",
                'startAt': "2020-05-25 00:00:00",
                'endAt': "2020-05-25 00:00:00",
                'site': 'url',
                'content': ''
                # 'duration': "Alternance"
            },
        ]
        





when@test:
    twig:
        strict_variables: true
