twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        SITE_NAME: Pierre Pineau
        CONTACT_EMAIL: contact@pierrepineau.fr
        CLIENT_FAVICON_COLOR: "#419FCC"
        CLIENT_FAVICON_BG: "#1f272f"
        socials: [
            {
                'icon': "fa-brands fa-linkedin-in",
                'name': "Me contacter sur linkedin",
                'url': "https://www.linkedin.com/in/pierre-pineau-pro/",
            },
        ]
        menu: [
            {
                'name': "À propos de moi",
                'url': "#a-propos",
            },
            {
                'name': "Expériences",
                'url': "#experiences",
            },
            {
                'name': "Réalisations",
                'url': "#realisations",
            },
            {
                'name': "Compétences",
                'url': "#competences",
            },
            {
                'name': "Contact",
                'url': "#contact",
            }
        ]
        statistics: [
            {
                'name': "d'expérience professionnelle",
                'value': "2 ans",
            },
            {
                'name': "lorem ipusm dolor sit",
                'value': "15",
            },
            {
                'name': "lorem ipusm dolor sit",
                'value': "+200 h",
            },
        ]

        specialties: [
            {
                'icon': "fa-solid fa-layer-group",
                'name': "Lorem ipusm dolor sit",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-layer-group",
                'name': "Lorem ipusm dolor sit",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-layer-group",
                'name': "Lorem ipusm dolor sit",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            },
            {
                'icon': "fa-solid fa-layer-group",
                'name': "Lorem ipusm dolor sit",
                'content': "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Libero non reprehenderit accusamus possimus, voluptatem dolorum minus aliquam ipsam quos!",
            }
        ]
        skills: [
            {
                'icon': "fa-brands fa-symfony",
                'name': "Symfony",
                'value': 80,
            },
            {
                'icon': "fa-brands fa-laravel",
                'name': "Laravel",
                'value': 55,
            },
            {
                'icon': "fa-brands fa-vuejs",
                'name': "VueJS",
                'value': 50,
            },
            {
                'icon': "fa-solid fa-file-code",
                'name': "Tailwind",
                'value': 90,
            },
            {
                'icon': "fa-brands fa-square-js",
                'name': "Javascript",
                'value': 90,
            },
            {
                'icon': "fa-solid fa-code",
                'name': "TWIG",
                'value': 80,
            },
        ]

        works: [
            {
                'name': work.innovdata.name,
                'job': work.job.dev,
                'type': work.type.alternance,
                'startAt': "2021-08-25 00:00:00",
                'endAt': null,
                'site': 'https://innov-data.com/',
                'content': work.innovdata.content
                # 'duration': "Alternance"
            },
            {
                'name': work.expertviseo.name,
                'job': work.job.dev,
                'type': work.type.stage,
                'startAt': "2020-04-29 00:00:00",
                'endAt': "2020-06-29 00:00:00",
                'site': 'https://www.expert-viseo.fr/',
                'content': work.expertviseo.content
                # 'duration': "Alternance"
            },
        ]

        projects: [
            {
                'name': "Find Your Horse",
                'thumbnail': find-your-horse.png,
                'url': "https://www.find-your-horse.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Find Your Horse",
                'thumbnail': find-your-horse.png,
                'url': "https://www.find-your-horse.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Find Your Horse",
                'thumbnail': find-your-horse.png,
                'url': "https://www.find-your-horse.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
            {
                'name': "Find Your Horse",
                'thumbnail': find-your-horse.png,
                'url': "https://www.find-your-horse.fr/",
                'content': "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ipsa, rem repellat? Veniam obcaecati in eius, architecto nisi explicabo id amet? Quasi ipsa quod sapiente aperiam dolorum quam molestias, nam nesciunt"
            },
        ]
        

when@test:
    twig:
        strict_variables: true
