name: FTP Sync

on:
  push:
    branches:
      - master

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        # uses: jakejarvis/ftp-sync-action@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: '/www/'
      # - name: Install dependencies
      #   run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      # - name: Clear Symfony cache
      #   run: php bin/console cache:clear